### PR TITLE
Refactoring code, Indentation, Use of the function in mapDispatchToProps, Add TextInput with the label by react-native-paper

### PR DESCRIPTION
**Pull request by Angelk90**
Refactoring code, Indentation, Use of the function in mapDispatchToProps, Add TextInput with the label by react-native-paper

### CODE REVIEW

**Comment by Angelk90** [comment]
@winit30 : Let me know if I can help you in any way.

**Comment by winit30** [comment]
Sure will let you know

**Comment by Saurabh-Biware** [comment]
response.text() is not a function . (In response.text(), response.text is undefined.


Screenshot_1564642188

**Comment by Angelk90** [comment]
@Saurabh-Biware : Would it be the registration page?
Did you use the original updated code or the one with the changes made by me?

**Comment by NameeshaFernando** [comment]
I also get that signup error.
i can't find a way to resolve that ?

**Comment by winit30** [comment]
Guys screenshots?

**Comment by winit30** [comment]
Okay will fix this weekend.

**Comment by Angelk90** [comment]
@winit30 : Is there any news on how to resume the tutorial series?

**Pull request closed without merging**
